// Configuration and Constants
export const MATERIALS = [
  "WOODEN_SWORD",
  "STONE_SWORD",
  "IRON_SWORD",
  "GOLDEN_SWORD",
  "DIAMOND_SWORD",
  "NETHERITE_SWORD",
  "WOODEN_AXE",
  "STONE_AXE",
  "IRON_AXE",
  "GOLDEN_AXE",
  "DIAMOND_AXE",
  "NETHERITE_AXE",
  "WOODEN_PICKAXE",
  "STONE_PICKAXE",
  "IRON_PICKAXE",
  "GOLDEN_PICKAXE",
  "DIAMOND_PICKAXE",
  "NETHERITE_PICKAXE",
  "BOW",
  "CROSSBOW",
  "TRIDENT",
  "SHIELD",
  "ELYTRA",
  "FISHING_ROD",
  "LEATHER_HELMET",
  "LEATHER_CHESTPLATE",
  "LEATHER_LEGGINGS",
  "LEATHER_BOOTS",
  "IRON_HELMET",
  "IRON_CHESTPLATE",
  "IRON_LEGGINGS",
  "IRON_BOOTS",
  "DIAMOND_HELMET",
  "DIAMOND_CHESTPLATE",
  "DIAMOND_LEGGINGS",
  "DIAMOND_BOOTS",
  "NETHERITE_HELMET",
  "NETHERITE_CHESTPLATE",
  "NETHERITE_LEGGINGS",
  "NETHERITE_BOOTS",
  "DIAMOND",
  "EMERALD",
  "GOLD_INGOT",
  "IRON_INGOT",
  "NETHERITE_INGOT",
  "COAL",
  "REDSTONE",
  "EXPERIENCE_BOTTLE",
  "NETHER_STAR",
  "BEACON",
  "TOTEM_OF_UNDYING",
  "ENCHANTED_BOOK",
  "PLAYER_HEAD",
  "STONE",
  "COBBLESTONE",
  "GRASS_BLOCK",
  "DIRT",
  "CHEST",
  "ENDER_CHEST",
  "OBSIDIAN",
];

export const REQUIREMENT_TEMPLATES = {
  playtime: {
    placeholder: "%statistic_play_one_minute%",
    type: "NUMBER",
    eval: "GREATER",
    guiMessage:
      "&7Playtime: &a%formatter_number_shorten_{current}%&7/&e%formatter_number_shorten_{required}% &r%status%",
    denyMessage: "&7You need more playtime to rank up",
  },
  money: {
    placeholder: "%vault_eco_balance%",
    type: "NUMBER",
    eval: "GREATER",
    guiMessage:
      "&7Money &a%formatter_number_shorten_{current}%&7/&e%formatter_number_shorten_{required}% &r%status%",
    denyMessage: "&7You need more money",
  },
  kills: {
    placeholder: "%statistic_player_kills%",
    type: "NUMBER",
    eval: "GREATER",
    guiMessage: "&7Kills: &a%current%&7/&e%required% &r%status%",
    denyMessage: "&7You need more kills",
  },
  level: {
    placeholder: "%player_level%",
    type: "NUMBER",
    eval: "GREATER",
    guiMessage: "&7Level: &a%current%&7/&e%required% &r%status%",
    denyMessage: "&7You need to be a higher level",
  },
  blocks: {
    placeholder: "%statistic_mine_block%",
    type: "NUMBER",
    eval: "GREATER",
    guiMessage:
      "&7Blocks: &a%formatter_number_shorten_{current}%&7/&e%formatter_number_shorten_{required}% &r%status%",
    denyMessage: "&7You need to break more blocks",
  },
};

export const QUICK_COMMANDS = {
  luckperms: (rankName) => `lp user %player% parent set ${rankName}`,
  economy: () => "eco give %player% 1000",
  title: (displayName) => `title %player% title "${displayName}"`,
  discord: (displayName) =>
    `discord: :medal: %player% has reached ${displayName}!`,
  kit: (rankName) =>
    `lp user %player% permission set essentials.kits.${rankName.toLowerCase()} true`,
  custom: () => "",
};
